### PR TITLE
Editing/polish of microarray heatmap notebook

### PR DESCRIPTION
**Pull request by jashapiro**
### Purpose

This PR is born out of #289 and #290, as I read through the heatmap example for content and display issues. I did this based mostly on what was currently rendered on github pages as a baseline for ease of reading, though I do not think that is far behind what is in `staging` in this case.  All of the changes here though are of course based off `staging`.  

There were no major content changes I would suggest, so I mostly made small edits here. (Also a couple in the intro)

Many of the are streamlining of code comments, which is largely to address #406. 

#### Gotchas the reviewer should know about

Are the code comments still sufficiently clear and informative?

## Remaining concerns and questions

To the extent that some of those changes are in common template material, they should be translated to those sections in a later PR or PRs, but this seemed a good place to test them out.

### CODE REVIEW

**Comment by jashapiro** [comment]
One other thought was with the use of `read_tsv()`; do we want to show the output of the column specification every time? I can make an argument either way, so I did not change it here, but I could see doing so. We do show the table later, so maybe that is sufficient?

**Comment by cansavvy** [comment]
> One other thought was with the use of `read_tsv()`; do we want to show the output of the column specification every time? I can make an argument either way, so I did not change it here, but I could see doing so. We do show the table later, so maybe that is sufficient?

I've seen some training participants see the output from `read_tsv()` and think its an error. So if we hide those messages from them, I think we are increasing the chances that when the user tries to run `read_tsv()` on their own they will be surprised by the output and think they've done something wrong. 

I think hiding some stuff is okay so we make it pretty, but I think we want them to see the normal output for other things so when they move to another chunk or notebook they aren't shocked about all the output we've hidden from them.

**Comment by jashapiro** [comment]
> I've seen some training participants see the output from `read_tsv()` and think its an error. So if we hide those messages from them, I think we are increasing the chances that when the user tries to run `read_tsv()` on their own they will be surprised by the output and think they've done something wrong.

This was the main reason I had not to remove it. I was thinking about suppressing the output not with `message = FALSE` but with `read_tsv(file, col_types = cols())` with a comment that including the second line is to avoid wordy output.

**Review by jaclyn-taroni — APPROVED** [review]
👍 LGTM. The inline nature of the `Replace ...` comments were from user feedback (#99; you may have already been aware of this issue), but it doesn't seem like there's a way to do both.

**Comment by jashapiro** [comment]
Added a bit more commentary on why microarrays are awesome wrt refine.bio to address #296 . Thoughts?

**Review by jaclyn-taroni — APPROVED** [review]
Most recent changes wrt #296 LGTM!

**Pull request merged**
