### PR TITLE
Create docker build workflow

### PR DESCRIPTION
**Pull request by jashapiro**
## Purpose:
This draft PR is to test automatic docker builds through github actions.
Partially addresses #236 

## Strategy
Modify the blank workflow to build the docker image instead.

To prevent the full repository from going into the build context, I moved the Docker file to a subdirectory.

## Concerns/Questions for reviewers:

Does it work?

### CODE REVIEW

**Comment by jashapiro** [comment]
It works! Takes 14 minutes with no caching. About to test using github caching actions, using example from https://github.com/docker/build-push-action#leverage-github-cache

**Comment by jashapiro** [comment]
Using the github cache adds some overhead, but it does speed things up in general: rebuilding (with reinstallation of python packages since I changed the ordering there) took ~5 minutes, including pulling from the cache and posting to it.

Note that the cache has a size limit of 5GB (compressed, I think), if we think we are likely to hit this with docker images, we might think about another solution. I don't know how to check the current cache usage...

**Comment by jaclyn-taroni** [comment]
Seems pretty easy for us to roll back the changes to building without caching (https://github.com/AlexsLemonade/refinebio-examples/pull/237/commits/b40b0ce44cb979b2f2b80c6efd6a55ec5d80b4f2) should we run into an issue, so I say let's try it! I assume addressing #235 will help us keep the cache size down, too..

**Comment by jashapiro** [comment]
Having now update `CONTRIBUTING.md` with the new Dockerfile path, I am now marking this ready for review. 

Running the Build action with no changes to the Dockerfile takes ~4.5 minutes. Most of that seems to be uncompressing and recompressing the cache files.

Oh, and the cache size is reported in the action logs as ~1536 MB. (Not sure if that is just this item, or total, but it doesn't matter in this case/)

**Review by jaclyn-taroni — APPROVED** [review]
One comment that's not easily made in-line on this PR! Should we get rid of (lines 8-9):

```yaml
  push:
    branches: [ master ]
```

For the moment. That is a remnant of the hello world template I used so we could get enforcing up to date branches up and running and I don't see a reason we would need to build things after we merge.

Otherwise, LGTM 👍

**Comment by jashapiro** [comment]
> One comment that's not easily made in-line on this PR! Should we get rid of (lines 8-9):
> 
> 
> 
> ```yaml
> 
>   push:
> 
>     branches: [ master ]
> 
> ```
> 
> 
> 
> For the moment. That is a remnant of the hello world template I used so we could get enforcing up to date branches up and running and I don't see a reason we would need to build things after we merge.
> 
> 
> 
> Otherwise, LGTM 👍 

I left it just in case... I was thinking we would make a separate action for pushes to master that does a full build (no cache?) and pushes to dockerhub.

**Comment by jaclyn-taroni** [comment]
> I was thinking we would make a separate action for pushes to master that does a full build (no cache?) and pushes to dockerhub.

This sounds good - separate action was what I was thinking, too, and it makes sense that we are not particularly concerned with how long that one will take.

**Comment by jaclyn-taroni** [comment]
Just remembered I added a section to the contributing guidelines that covers status checks: https://github.com/AlexsLemonade/refinebio-examples/blob/master/CONTRIBUTING.md#pull-request-status-checks

To quote myself from #222

> In 6 months, we might forget that that isn't _really doing anything_ so I wrote something about it in the contributing guidelines.

We should probably update this section to reflect what this is now doing with these changes.

**Review by jaclyn-taroni — APPROVED** [review]
🚢

**Pull request merged**
