### PR TITLE
Staging -> Master

### PR DESCRIPTION
**Pull request by cansavvy**
## Purpose:
This should bring master up to date with the most recent PRs: 

#314 and #311 

It's also a good test for how the gha's mechanics are working for this kind of merge.

### CODE REVIEW

**Comment by cansavvy** [comment]
I expected this would be checking out `gh-pages` but it is still checking out `gh-pages-stages` Upon merging will this be the correct branch though?? @jashapiro 
`https://github.com/AlexsLemonade/refinebio-examples/pull/320/checks?check_run_id=1288999328

**Comment by cansavvy** [comment]
I think maybe it should be `github.base_ref` since here both the branch and the base branch are something that initiates github actions from the `on:` criteria?

**Comment by jashapiro** [comment]
> I expected this would be checking out `gh-pages` but it is still checking out `gh-pages-stages` Upon merging will this be the correct branch though?? @jashapiro
> `https://github.com/AlexsLemonade/refinebio-examples/pull/320/checks?check_run_id=1288999328

I think this is correct. This was triggered by the push to `staging` not the PR. (This also means that `github.base_ref` will not be defined)

Most of the time this should not come up, as we should not generally be committing directly to `staging` as it appears you did here to merge from `master`?

**Comment by cansavvy** [comment]
> > I expected this would be checking out `gh-pages` but it is still checking out `gh-pages-stages` Upon merging will this be the correct branch though?? @jashapiro
> 
> > `https://github.com/AlexsLemonade/refinebio-examples/pull/320/checks?check_run_id=1288999328
> 
> 
> 
> I think this is correct. This was triggered by the push to `staging` not the PR. (This also means that `github.base_ref` will not be defined)

Ah right. 


> Most of the time this should not come up, as we should not generally be committing directly to `staging` as it appears you did here to merge from `master`?


We would be committing directly to staging and then to master? This is more representative of what the process will look like.

**Comment by jashapiro** [comment]
> We would be committing directly to staging and then to master?

We would be committing to `staging` via a PR, then merging to `master` from there. Or more likely, we would be creating a different new branch which consists of particular files/commits that have been tested in staging (to avoid irrelevant changes that might have gone into staging for another purpose)?. I think this process still needs discussion in #313.

**Comment by cansavvy** [comment]
> I think this process still needs discussion in #313.

Besides the discussions of other instances of this kind of PR (that are happening elsewhere (#313), is there anything to this particular PR that needs adjusting before we merge?

**Comment by jashapiro** [comment]
I am not going to approve this PR; I think we need to follow a staging->branch->master strategy. Otherwise this PR keeps getting new commits as more changes get pushed in, so an approval might not reflect the current contents.

Right now there is at least one conflict, and resolving it does not make sense within the branch (and should actually not be allowed).

**Comment by cansavvy** [comment]
> I am not going to approve this PR; I think we need to follow a staging->branch->master strategy. Otherwise this PR keeps getting new commits as more changes get pushed in, so an approval might not reflect the current contents.
> 
> Right now there is at least one conflict, and resolving it does not make sense within the branch (and should actually not be allowed).

Okay. Yes. I’ve been noticing these conflicts. I think what you say makes sense. Will readjust this and clarify on #313

**Comment by cansavvy** [comment]
Will reconfigure this PR. As is, the conflict resolutions make this not an ideal situation (can't be committing directly to staging!). So will try a "cherry pick" and make a new branch strategy.

**Pull request closed without merging**
