### PR TITLE
Add CITATION.cff

### LINKED ISSUE #470: Cut a new release and add CITATION.cff
`CITATION.cff` supports versioning, but our most recent release is v1.0. We should cut a new release and then add a `CITATION.cff` to the root of the repo using largely the same logic as in https://github.com/AlexsLemonade/training-modules/pull/498

### PR DESCRIPTION
**Pull request by jaclyn-taroni**
Closes #470 - here I'm adding `CITATION.cff` where I use the order of: https://github.com/AlexsLemonade/refinebio-examples/graphs/contributors

With the exception that I am last (similar to what we did in: https://github.com/AlexsLemonade/training-modules/pull/498)

### CODE REVIEW

**Comment by jaclyn-taroni** [comment]
Tagging @cansavvy to +1 this one, too 😁

**Review by davidsmejia — APPROVED** [review]

**Review by jashapiro — APPROVED** [review]
👍🏼

**Review by cbethell — APPROVED** [review]
✅

**Review by dvenprasad — APPROVED** [review]
🦉 🦉 🦉

**Comment by cansavvy** [comment]
This looks good to me!

**Pull request merged**
