### PR TITLE
Publish WGCNA example!

### PR DESCRIPTION
**Pull request by cansavvy**
## Changes Being Published

This is a test to only add WGCNA by itself

I made a branch off of master and cherry picked these WGCNA commits. 

## List of Commits/PR's Included

- All 6 parts of WGCNA example: #358 #360 #363 #364 #379 , and #382 
- As well as the docker fix #366 

## Link to html Preview

For reviewing purposes, you can take a browse through htmlpreview: http://htmlpreview.github.io/?https://github.com/AlexsLemonade/refinebio-examples/gh-pages-stages/01-getting-started/getting-started.html

## Publishing Checklist:

- [x] Does everything look good using html preview -- having taken a particularly close look at any new html files?

- [x] Have any new examples been added to the [refinebio-examples feedback survey](https://app.hubspot.com/forms/5187852/a50f293c-1ef4-4ee1-b7ee-c563afe2ad5c/performance)? Ideally, don't click publish until this PR is merged (changes are autosaved).

### CODE REVIEW

**Comment by cansavvy** [comment]
Some spelling errors are back? https://github.com/AlexsLemonade/refinebio-examples/pull/384/checks?check_run_id=1480673832

**Comment by jashapiro** [comment]
I was assuming you would do the other changes first? My guess is that there are dictionary changes in other PRs.

**Comment by cansavvy** [comment]
> I was assuming you would do the other changes first?

It seemed easiest to cherry pick example's commits since those are all properly squashed. And then when we get to #383 It should only have the "other changes" left. (So I can do this same thing for GSEA and GSVA examples).

**Comment by jashapiro** [comment]
> It seemed easiest to cherry pick example's commits since those are all properly squashed.

In general yes, but since a lot of those changes expect earlier ones, I would for now do those first. My thought was to get all the messy commits done first, then move on to the nice modular and squashed ones. I was thinking you would start with a new branch to do what was in #383, but without WCGNA. Then we do WCGNA to test the future process with squashed commits.

**Comment by cansavvy** [comment]
> > It seemed easiest to cherry pick example's commits since those are all properly squashed.
> 
> In general yes, but since a lot of those changes expect earlier ones, I would for now do those first. My thought was to get all the messy commits done first, then move on to the nice modular and squashed ones. I was thinking you would start with a new branch to do what was in #383, but without WCGNA. Then we do WCGNA to test the future process with squashed commits.

AH. Yeah, I suppose that makes sense. Let me try this out then.

**Review by jashapiro — APPROVED** [review]
This looks good to me! If the checks ever pass...

**Pull request merged**
